# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('venue', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField()),
                ('uri', models.CharField(max_length=128)),
            ],
        ),
    ]
